In [1]:
import numpy as np 
import pandas as pd

C:\Users\shriy\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [16]:
movies = movies.merge(credits, on='title')

In [17]:
# useful columns
# genres
# id
# keywords
# title
# overview
# release_date --> now now but later on
# cast
# crew

In [20]:
movies=movies[['movie_id','title', 'overview', 'genres','keywords','cast','crew']]

In [21]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4845 entries, 0 to 4844
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4845 non-null   int64
 1   title     4845 non-null   object
 2   overview  4842 non-null   object
 3   genres    4845 non-null   object
 4   keywords  4845 non-null   object
 5   cast      4845 non-null   object
 6   crew      4845 non-null   object
dtypes: int64(1), object(6)
memory usage: 265.1+ KB

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [25]:
movies.dropna(inplace=True)

In [34]:
movies.duplicated().sum()

36

In [35]:
duplicates = movies[movies.duplicated()]
print(duplicates)

      movie_id            title  \
974      72710         The Host
975       1255         The Host
976      72710         The Host
977       1255         The Host
978      72710         The Host
979       1255         The Host
1368       268           Batman
1369      2661           Batman
1370       268           Batman
1371      2661           Batman
1372       268           Batman
1373      2661           Batman
2893     72710         The Host
2894      1255         The Host
2895     72710         The Host
2896      1255         The Host
2897     72710         The Host
2898      1255         The Host
3670     39269  Out of the Blue
3671     10844  Out of the Blue
3672     39269  Out of the Blue
3673     10844  Out of the Blue
3674     39269  Out of the Blue
3675     10844  Out of the Blue
3723     39269  Out of the Blue
3724     10844  Out of the Blue
3725     39269  Out of the Blue
3726     10844  Out of the Blue
3727     39269  Out of the Blue
3728     10844  Out of the Blue
4304       268           Batman
4305      2661           Batman
4306       268           Batman
4307      2661           Batman
4308       268           Batman
4309      2661           Batman

                                               overview  \
974   A parasitic alien soul is injected into the bo...
975   A parasitic alien soul is injected into the bo...
976   A parasitic alien soul is injected into the bo...
977   A parasitic alien soul is injected into the bo...
978   A parasitic alien soul is injected into the bo...
979   A parasitic alien soul is injected into the bo...
1368  The Dark Knight of Gotham City begins his war ...
1369  The Dark Knight of Gotham City begins his war ...
1370  The Dark Knight of Gotham City begins his war ...
1371  The Dark Knight of Gotham City begins his war ...
1372  The Dark Knight of Gotham City begins his war ...
1373  The Dark Knight of Gotham City begins his war ...
2893  Gang-du is a dim-witted man working at his fat...
2894  Gang-du is a dim-witted man working at his fat...
2895  Gang-du is a dim-witted man working at his fat...
2896  Gang-du is a dim-witted man working at his fat...
2897  Gang-du is a dim-witted man working at his fat...
2898  Gang-du is a dim-witted man working at his fat...
3670  Dennis Hopper is a hard-drinking truck driver ...
3671  Dennis Hopper is a hard-drinking truck driver ...
3672  Dennis Hopper is a hard-drinking truck driver ...
3673  Dennis Hopper is a hard-drinking truck driver ...
3674  Dennis Hopper is a hard-drinking truck driver ...
3675  Dennis Hopper is a hard-drinking truck driver ...
3723  Ordinary people find extraordinary courage in ...
3724  Ordinary people find extraordinary courage in ...
3725  Ordinary people find extraordinary courage in ...
3726  Ordinary people find extraordinary courage in ...
3727  Ordinary people find extraordinary courage in ...
3728  Ordinary people find extraordinary courage in ...
4304  The Dynamic Duo faces four super-villains who ...
4305  The Dynamic Duo faces four super-villains who ...
4306  The Dynamic Duo faces four super-villains who ...
4307  The Dynamic Duo faces four super-villains who ...
4308  The Dynamic Duo faces four super-villains who ...
4309  The Dynamic Duo faces four super-villains who ...

                                                 genres  \
974   [{"id": 28, "name": "Action"}, {"id": 12, "nam...
975   [{"id": 28, "name": "Action"}, {"id": 12, "nam...
976   [{"id": 28, "name": "Action"}, {"id": 12, "nam...
977   [{"id": 28, "name": "Action"}, {"id": 12, "nam...
978   [{"id": 28, "name": "Action"}, {"id": 12, "nam...
979   [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1368  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
1369  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
1370  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
1371  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
1372  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
1373  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
2893  [{"id": 27, "name": "Horror"}, {"id": 18, "nam...
2894  [{"id": 27, "name": "Horror"}, {"id": 18, "nam...
2895  [{"id": 27, "name": "Horror"}, {"id": 18, "nam...
2896  [{"id": 27, "name": "Horror"}, {"id": 18, "nam...
2897  [{"id": 27, "name": "Horror"}, {"id": 18, "nam...
2898  [{"id": 27, "name": "Horror"}, {"id": 18, "nam...
3670                      [{"id": 18, "name": "Drama"}]
3671                      [{"id": 18, "name": "Drama"}]
3672                      [{"id": 18, "name": "Drama"}]
3673                      [{"id": 18, "name": "Drama"}]
3674                      [{"id": 18, "name": "Drama"}]
3675                      [{"id": 18, "name": "Drama"}]
3723                      [{"id": 18, "name": "Drama"}]
3724                      [{"id": 18, "name": "Drama"}]
3725                      [{"id": 18, "name": "Drama"}]
3726                      [{"id": 18, "name": "Drama"}]
3727                      [{"id": 18, "name": "Drama"}]
3728                      [{"id": 18, "name": "Drama"}]
4304  [{"id": 10751, "name": "Family"}, {"id": 12, "...
4305  [{"id": 10751, "name": "Family"}, {"id": 12, "...
4306  [{"id": 10751, "name": "Family"}, {"id": 12, "...
4307  [{"id": 10751, "name": "Family"}, {"id": 12, "...
4308  [{"id": 10751, "name": "Family"}, {"id": 12, "...
4309  [{"id": 10751, "name": "Family"}, {"id": 12, "...

                                               keywords  \
974   [{"id": 818, "name": "based on novel"}, {"id":...
975   [{"id": 818, "name": "based on novel"}, {"id":...
976   [{"id": 818, "name": "based on novel"}, {"id":...
977   [{"id": 818, "name": "based on novel"}, {"id":...
978   [{"id": 818, "name": "based on novel"}, {"id":...
979   [{"id": 818, "name": "based on novel"}, {"id":...
1368  [{"id": 848, "name": "double life"}, {"id": 84...
1369  [{"id": 848, "name": "double life"}, {"id": 84...
1370  [{"id": 848, "name": "double life"}, {"id": 84...
1371  [{"id": 848, "name": "double life"}, {"id": 84...
1372  [{"id": 848, "name": "double life"}, {"id": 84...
1373  [{"id": 848, "name": "double life"}, {"id": 84...
2893  [{"id": 1261, "name": "river"}, {"id": 1880, "...
2894  [{"id": 1261, "name": "river"}, {"id": 1880, "...
2895  [{"id": 1261, "name": "river"}, {"id": 1880, "...
2896  [{"id": 1261, "name": "river"}, {"id": 1880, "...
2897  [{"id": 1261, "name": "river"}, {"id": 1880, "...
2898  [{"id": 1261, "name": "river"}, {"id": 1880, "...
3670  [{"id": 4470, "name": "punk"}, {"id": 10183, "...
3671  [{"id": 4470, "name": "punk"}, {"id": 10183, "...
3672  [{"id": 4470, "name": "punk"}, {"id": 10183, "...
3673  [{"id": 4470, "name": "punk"}, {"id": 10183, "...
3674  [{"id": 4470, "name": "punk"}, {"id": 10183, "...
3675  [{"id": 4470, "name": "punk"}, {"id": 10183, "...
3723  [{"id": 2658, "name": "new zealand"}, {"id": 3...
3724  [{"id": 2658, "name": "new zealand"}, {"id": 3...
3725  [{"id": 2658, "name": "new zealand"}, {"id": 3...
3726  [{"id": 2658, "name": "new zealand"}, {"id": 3...
3727  [{"id": 2658, "name": "new zealand"}, {"id": 3...
3728  [{"id": 2658, "name": "new zealand"}, {"id": 3...
4304  [{"id": 339, "name": "submarine"}, {"id": 849,...
4305  [{"id": 339, "name": "submarine"}, {"id": 849,...
4306  [{"id": 339, "name": "submarine"}, {"id": 849,...
4307  [{"id": 339, "name": "submarine"}, {"id": 849,...
4308  [{"id": 339, "name": "submarine"}, {"id": 849,...
4309  [{"id": 339, "name": "submarine"}, {"id": 849,...

                                                   cast  \
974   [{"cast_id": 52, "character": "Melanie Stryder...
975   [{"cast_id": 3, "character": "Park Gang-du", "...
976   [{"cast_id": 52, "character": "Melanie Stryder...
977   [{"cast_id": 3, "character": "Park Gang-du", "...
978   [{"cast_id": 52, "character": "Melanie Stryder...
979   [{"cast_id": 3, "character": "Park Gang-du", "...
1368  [{"cast_id": 5, "character": "Jack Napier/The ...
1369  [{"cast_id": 17, "character": "Batman / Bruce ...
1370  [{"cast_id": 5, "character": "Jack Napier/The ...
1371  [{"cast_id": 17, "character": "Batman / Bruce ...
1372  [{"cast_id": 5, "character": "Jack Napier/The ...
1373  [{"cast_id": 17, "character": "Batman / Bruce ...
2893  [{"cast_id": 52, "character": "Melanie Stryder...
2894  [{"cast_id": 3, "character": "Park Gang-du", "...
2895  [{"cast_id": 52, "character": "Melanie Stryder...
2896  [{"cast_id": 3, "character": "Park Gang-du", "...
2897  [{"cast_id": 52, "character": "Melanie Stryder...
2898  [{"cast_id": 3, "character": "Park Gang-du", "...
3670  [{"cast_id": 2, "character": "Don", "credit_id...
3671  [{"cast_id": 12, "character": "Nick Harvey", "...
3672  [{"cast_id": 2, "character": "Don", "credit_id...
3673  [{"cast_id": 12, "character": "Nick Harvey", "...
3674  [{"cast_id": 2, "character": "Don", "credit_id...
3675  [{"cast_id": 12, "character": "Nick Harvey", "...
3723  [{"cast_id": 2, "character": "Don", "credit_id...
3724  [{"cast_id": 12, "character": "Nick Harvey", "...
3725  [{"cast_id": 2, "character": "Don", "credit_id...
3726  [{"cast_id": 12, "character": "Nick Harvey", "...
3727  [{"cast_id": 2, "character": "Don", "credit_id...
3728  [{"cast_id": 12, "character": "Nick Harvey", "...
4304  [{"cast_id": 5, "character": "Jack Napier/The ...
4305  [{"cast_id": 17, "character": "Batman / Bruce ...
4306  [{"cast_id": 5, "character": "Jack Napier/The ...
4307  [{"cast_id": 17, "character": "Batman / Bruce ...
4308  [{"cast_id": 5, "character": "Jack Napier/The ...
4309  [{"cast_id": 17, "character": "Batman / Bruce ...

                                                   crew
974   [{"credit_id": "52fe487bc3a368484e0fa919", "de...
975   [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
976   [{"credit_id": "52fe487bc3a368484e0fa919", "de...
977   [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
978   [{"credit_id": "52fe487bc3a368484e0fa919", "de...
979   [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
1368  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
1369  [{"credit_id": "52fe4363c3a36847f80509a7", "de...
1370  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
1371  [{"credit_id": "52fe4363c3a36847f80509a7", "de...
1372  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
1373  [{"credit_id": "52fe4363c3a36847f80509a7", "de...
2893  [{"credit_id": "52fe487bc3a368484e0fa919", "de...
2894  [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
2895  [{"credit_id": "52fe487bc3a368484e0fa919", "de...
2896  [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
2897  [{"credit_id": "52fe487bc3a368484e0fa919", "de...
2898  [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
3670  [{"credit_id": "52fe47099251416c9106826f", "de...
3671  [{"credit_id": "52fe43c19251416c7501cceb", "de...
3672  [{"credit_id": "52fe47099251416c9106826f", "de...
3673  [{"credit_id": "52fe43c19251416c7501cceb", "de...
3674  [{"credit_id": "52fe47099251416c9106826f", "de...
3675  [{"credit_id": "52fe43c19251416c7501cceb", "de...
3723  [{"credit_id": "52fe47099251416c9106826f", "de...
3724  [{"credit_id": "52fe43c19251416c7501cceb", "de...
3725  [{"credit_id": "52fe47099251416c9106826f", "de...
3726  [{"credit_id": "52fe43c19251416c7501cceb", "de...
3727  [{"credit_id": "52fe47099251416c9106826f", "de...
3728  [{"credit_id": "52fe43c19251416c7501cceb", "de...
4304  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
4305  [{"credit_id": "52fe4363c3a36847f80509a7", "de...
4306  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
4307  [{"credit_id": "52fe4363c3a36847f80509a7", "de...
4308  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
4309  [{"credit_id": "52fe4363c3a36847f80509a7", "de...

In [38]:
movies.dropna(inplace=True)

In [39]:
movies.duplicated().sum()

36

In [40]:
movies[movies.duplicated(subset="movie_id", keep=False)]

,movie_id,title,overview,genres,keywords,cast,crew
972,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
973,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
974,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
975,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
976,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
977,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
978,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
979,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
1366,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1367,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
1368,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1369,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
1370,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1371,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
1372,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1373,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
2891,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2892,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
2893,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2894,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
2895,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2896,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
2897,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2898,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
3668,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3669,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3670,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3671,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3672,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3673,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3674,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3675,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3721,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3722,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3723,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3724,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3725,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3726,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3727,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3728,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
4302,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4303,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
4304,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4305,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
4306,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4307,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
4308,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4309,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."

In [41]:
movies[movies.duplicated(subset="title", keep=False)]

,movie_id,title,overview,genres,keywords,cast,crew
972,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
973,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
974,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
975,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
976,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
977,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
978,72710,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
979,1255,The Host,A parasitic alien soul is injected into the bo...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
1366,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1367,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
1368,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1369,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
1370,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1371,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
1372,268,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
1373,2661,Batman,The Dark Knight of Gotham City begins his war ...,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
2891,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2892,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
2893,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2894,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
2895,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2896,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
2897,72710,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 52, ""character"": ""Melanie Stryder...","[{""credit_id"": ""52fe487bc3a368484e0fa919"", ""de..."
2898,1255,The Host,Gang-du is a dim-witted man working at his fat...,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...","[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...","[{""cast_id"": 3, ""character"": ""Park Gang-du"", ""...","[{""credit_id"": ""52fe42eac3a36847f802ca6b"", ""de..."
3668,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3669,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3670,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3671,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3672,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3673,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3674,39269,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3675,10844,Out of the Blue,Dennis Hopper is a hard-drinking truck driver ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 4470, ""name"": ""punk""}, {""id"": 10183, ""...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3721,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3722,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3723,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3724,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3725,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3726,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
3727,39269,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 2, ""character"": ""Don"", ""credit_id...","[{""credit_id"": ""52fe47099251416c9106826f"", ""de..."
3728,10844,Out of the Blue,Ordinary people find extraordinary courage in ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2658, ""name"": ""new zealand""}, {""id"": 3...","[{""cast_id"": 12, ""character"": ""Nick Harvey"", ""...","[{""credit_id"": ""52fe43c19251416c7501cceb"", ""de..."
4302,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4303,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
4304,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4305,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
4306,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4307,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."
4308,268,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 5, ""character"": ""Jack Napier/The ...","[{""credit_id"": ""52fe422fc3a36847f800aa4b"", ""de..."
4309,2661,Batman,The Dynamic Duo faces four super-villains who ...,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 12, ""...","[{""id"": 339, ""name"": ""submarine""}, {""id"": 849,...","[{""cast_id"": 17, ""character"": ""Batman / Bruce ...","[{""credit_id"": ""52fe4363c3a36847f80509a7"", ""de..."

In [42]:
movies = movies.drop_duplicates(subset="movie_id")

In [43]:
movies.duplicated().sum()

0

In [45]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [44]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [46]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action', 'Adventure', 'Fantasy', 'SciFi']

In [52]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [53]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [54]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [56]:
movies['genres']=movies['genres'].apply(convert)

C:\Users\shriy\AppData\Local\Temp\ipykernel_15844\1567952790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

In [57]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4840                        [Action, Crime, Thriller]
4841                                [Comedy, Romance]
4842               [Comedy, Drama, Romance, TV Movie]
4843                                               []
4844                                    [Documentary]
Name: genres, Length: 4800, dtype: object

In [58]:
movies['keywords']=movies['keywords'].apply(convert)

C:\Users\shriy\AppData\Local\Temp\ipykernel_15844\1621871954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(convert)

In [59]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4840    [united states–mexico barrier, legs, arms, pap...
4841                                                   []
4842    [date, love at first sight, narration, investi...
4843                                                   []
4844            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4800, dtype: object

In [60]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [61]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [62]:
def convert3(obj):
    L = []
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [65]:
movies['cast']=movies['cast'].apply(convert3)

In [66]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [68]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [69]:
def fetch_director(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        if i['job'] =='Director':
            L.append(i['name'])
            break
    
    return L

In [71]:
movies['crew']=movies['crew'].apply(fetch_director)

In [72]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [95]:
movies.overview[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [100]:
movies['overview'] = movies['overview'].str.split()

In [101]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [78]:
movies['genres']= movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']= movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']= movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']= movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [79]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [102]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [103]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [105]:
new_df=movies[['movie_id','title', 'tags']]

In [108]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\shriy\AppData\Local\Temp\ipykernel_15844\2363790582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [109]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [125]:
import nltk

In [127]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [132]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [138]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\shriy\AppData\Local\Temp\ipykernel_15844\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [110]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [112]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\shriy\AppData\Local\Temp\ipykernel_15844\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [113]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [139]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [140]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [141]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [145]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [143]:
ps.stem('danceing')

'danc'

In [144]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [146]:
from sklearn.metrics.pairwise import cosine_similarity

In [147]:
similarity = cosine_similarity(vectors)

In [151]:
sorted(list(enumerate(similarity[0])),reverse=True, key=lambda x:x[1])[1:6]

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3724, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957)]

In [149]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [159]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [161]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [163]:
!pip install streamlit
import streamlit as st

Collecting streamlit
  Obtaining dependency information for streamlit from https://files.pythonhosted.org/packages/e4/91/cb6f13a89e376ef179309d74f37a70ea0041d5e4b5ba5c4836dbf6e020ad/streamlit-1.56.0-py3-none-any.whl.metadata
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Obtaining dependency information for altair!=5.4.0,!=5.4.1,<7,>=4.0 from https://files.pythonhosted.org/packages/db/33/ef2f2409450ef6daa61459d5de5c08128e7d3edb773fefd0a324d1310238/altair-6.0.0-py3-none-any.whl.metadata
  Using cached altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Collecting cachetools<8,>=5.5 (from streamlit)
  Obtaining dependency information for cachetools<8,>=5.5 from https://files.pythonhosted.org/packages/06/f3/39cf3367b8107baa44f861dc802cbf16263c945b62d8265d36034fc07bea/cachetools-7.0.5-py3-none-any.whl.metadata
  Downloading cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging>=20 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (2.3.1)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (12.1.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Obtaining dependency information for pydeck<1,>=0.8.0b4 from https://files.pythonhosted.org/packages/ab/4c/b888e6cf58bd9db9c93f40d1c6be8283ff49d88919231afe93a6bcf61626/pydeck-0.9.1-py2.py3-none-any.whl.metadata
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow>=7.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (6.3.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (4.14.1)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\shriy\anaconda3\lib\site-packages (from streamlit) (2.1.6)
Requirement already satisfied: jinja2 in c:\users\shriy\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\shriy\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.0)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Obtaining dependency information for narwhals>=1.27.1 from https://files.pythonhosted.org/packages/3f/c3/06490e98393dcb4d6ce2bf331a39335375c300afaef526897881fbeae6ab/narwhals-2.18.1-py3-none-any.whl.metadata
  Downloading narwhals-2.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: colorama in c:\users\shriy\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\shriy\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shriy\anaconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shriy\anaconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shriy\anaconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2023.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shriy\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shriy\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shriy\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shriy\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2023.7.22)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\shriy\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shriy\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\shriy\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\shriy\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\shriy\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\shriy\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.27.0)
Requirement already satisfied: six>=1.5 in c:\users\shriy\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.16.0)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.1 MB 660.6 kB/s eta 0:00:14
   ---------------------------------------- 0.0/9.1 MB 281.8 kB/s eta 0:00:32
   ---------------------------------------- 0.1/9.1 MB 525.1 kB/s eta 0:00:18
   ---------------------------------------- 0.1/9.1 MB 525.1 kB/s eta 0:00:18
    --------------------------------------- 0.1/9.1 MB 502.3 kB/s eta 0:00:18
    --------------------------------------- 0.2/9.1 MB 525.1 kB/s eta 0:00:17
    --------------------------------------- 0.2/9.1 MB 525.1 kB/s eta 0:00:17
    --------------------------------------- 0.2/9.1 MB 525.1 kB/s eta 0:00:17
   - -------------------------------------- 0.2/9.1 MB 554.9 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.1 MB 568.9 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.1 MB 559.2 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.1 MB 559.2 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.1 MB 559.2 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.1 MB 559.2 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.1 MB 427.9 kB/s eta 0:00:21
   - -------------------------------------- 0.4/9.1 MB 464.2 kB/s eta 0:00:19
   -- ------------------------------------- 0.6/9.1 MB 694.7 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/9.1 MB 680.2 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/9.1 MB 680.2 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/9.1 MB 680.2 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/9.1 MB 680.2 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.1 MB 814.4 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.1 MB 814.4 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.1 MB 814.4 kB/s eta 0:00:11
   ---- ----------------------------------- 0.9/9.1 MB 749.1 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/9.1 MB 771.7 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/9.1 MB 767.4 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/9.1 MB 788.3 kB/s eta 0:00:11
   ---- ----------------------------------- 1.1/9.1 MB 796.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.1/9.1 MB 799.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.1/9.1 MB 799.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.1/9.1 MB 799.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.2/9.1 MB 782.5 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.1 MB 775.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.1 MB 779.1 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.1 MB 779.1 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.1 MB 779.1 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.1 MB 779.1 kB/s eta 0:00:10
   ----- ---------------------------------- 1.4/9.1 MB 733.8 kB/s eta 0:00:11
   ------ --------------------------------- 1.5/9.1 MB 813.7 kB/s eta 0:00:10
   ------ --------------------------------- 1.5/9.1 MB 813.7 kB/s eta 0:00:10
   ------ --------------------------------- 1.5/9.1 MB 813.7 kB/s eta 0:00:10
   ------ --------------------------------- 1.5/9.1 MB 813.7 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/9.1 MB 800.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/9.1 MB 800.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/9.1 MB 800.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/9.1 MB 800.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/9.1 MB 800.8 kB/s eta 0:00:10
   -------- ------------------------------- 1.8/9.1 MB 779.5 kB/s eta 0:00:10
   -------- ------------------------------- 1.8/9.1 MB 782.3 kB/s eta 0:00:10
   -------- ------------------------------- 1.8/9.1 MB 782.3 kB/s eta 0:00:10
   -------- ------------------------------- 1.9/9.1 MB 768.1 kB/s eta 0:00:10
   -------- ------------------------------- 1.9/9.1 MB 767.6 kB/s eta 0:00:10
   -------- ------------------------------- 1.9/9.1 MB 767.6 kB/s eta 0:00:10
   -------- ------------------------------- 1.9/9.1 MB 750.7 kB/s eta 0:00:10
   -------- ------------------------------- 2.0/9.1 MB 744.7 kB/s eta 0:00:10
   -------- ------------------------------- 2.0/9.1 MB 735.5 kB/s eta 0:00:10
   -------- ------------------------------- 2.0/9.1 MB 730.4 kB/s eta 0:00:10
   -------- ------------------------------- 2.0/9.1 MB 733.6 kB/s eta 0:00:10
   --------- ------------------------------ 2.0/9.1 MB 725.1 kB/s eta 0:00:10
   --------- ------------------------------ 2.0/9.1 MB 725.1 kB/s eta 0:00:10
   --------- ------------------------------ 2.0/9.1 MB 725.1 kB/s eta 0:00:10
   --------- ------------------------------ 2.1/9.1 MB 707.3 kB/s eta 0:00:10
   --------- ------------------------------ 2.1/9.1 MB 706.6 kB/s eta 0:00:10
   --------- ------------------------------ 2.1/9.1 MB 706.6 kB/s eta 0:00:10
   --------- ------------------------------ 2.2/9.1 MB 691.7 kB/s eta 0:00:10
   --------- ------------------------------ 2.2/9.1 MB 691.7 kB/s eta 0:00:10
   --------- ------------------------------ 2.2/9.1 MB 691.7 kB/s eta 0:00:10
   --------- ------------------------------ 2.2/9.1 MB 691.7 kB/s eta 0:00:10
   --------- ------------------------------ 2.2/9.1 MB 671.0 kB/s eta 0:00:11
   --------- ------------------------------ 2.2/9.1 MB 671.1 kB/s eta 0:00:11
   --------- ------------------------------ 2.2/9.1 MB 661.4 kB/s eta 0:00:11
   --------- ------------------------------ 2.3/9.1 MB 652.5 kB/s eta 0:00:11
   --------- ------------------------------ 2.3/9.1 MB 652.5 kB/s eta 0:00:11
   --------- ------------------------------ 2.3/9.1 MB 652.5 kB/s eta 0:00:11
   --------- ------------------------------ 2.3/9.1 MB 652.5 kB/s eta 0:00:11
   --------- ------------------------------ 2.3/9.1 MB 652.5 kB/s eta 0:00:11
   ---------- ----------------------------- 2.3/9.1 MB 627.3 kB/s eta 0:00:11
   ---------- ----------------------------- 2.3/9.1 MB 624.8 kB/s eta 0:00:11
   ---------- ----------------------------- 2.3/9.1 MB 624.8 kB/s eta 0:00:11
   ---------- ----------------------------- 2.3/9.1 MB 609.7 kB/s eta 0:00:12
   ---------- ----------------------------- 2.3/9.1 MB 609.7 kB/s eta 0:00:12
   ---------- ----------------------------- 2.3/9.1 MB 599.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.3/9.1 MB 599.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 595.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 595.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 584.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 584.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 571.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 571.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 568.1 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 560.1 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 560.1 kB/s eta 0:00:12
   ---------- ----------------------------- 2.4/9.1 MB 550.8 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/9.1 MB 550.8 kB/s eta 0:00:13
   ---------- ----------------------------- 2.5/9.1 MB 549.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.5/9.1 MB 549.6 kB/s eta 0:00:12
   ---------- ----------------------------- 2.5/9.1 MB 538.7 kB/s eta 0:00:13
   ---------- ----------------------------- 2.5/9.1 MB 538.7 kB/s eta 0:00:13
   ---------- ----------------------------- 2.5/9.1 MB 530.5 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 525.6 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 525.6 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 521.4 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 518.8 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 518.8 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 518.8 kB/s eta 0:00:13
   ----------- ---------------------------- 2.5/9.1 MB 509.5 kB/s eta 0:00:13
   ----------- ---------------------------- 2.6/9.1 MB 507.3 kB/s eta 0:00:13
   ----------- ---------------------------- 2.6/9.1 MB 507.3 kB/s eta 0:00:13
   ----------- ---------------------------- 2.6/9.1 MB 507.3 kB/s eta 0:00:13
   ----------- ---------------------------- 2.6/9.1 MB 507.3 kB/s eta 0:00:13
   ----------- ---------------------------- 2.6/9.1 MB 495.0 kB/s eta 0:00:14
   ----------- ---------------------------- 2.6/9.1 MB 495.0 kB/s eta 0:00:14
   ----------- ---------------------------- 2.6/9.1 MB 490.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.6/9.1 MB 490.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.6/9.1 MB 482.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.6/9.1 MB 482.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.6/9.1 MB 482.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 475.0 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 470.2 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 470.2 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 466.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 466.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 466.1 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 460.9 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 457.7 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 457.7 kB/s eta 0:00:14
   ----------- ---------------------------- 2.7/9.1 MB 457.7 kB/s eta 0:00:14
   ------------ --------------------------- 2.7/9.1 MB 452.8 kB/s eta 0:00:14
   ------------ --------------------------- 2.7/9.1 MB 447.5 kB/s eta 0:00:15
   ------------ --------------------------- 2.7/9.1 MB 447.5 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 447.5 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 447.5 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 442.9 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 442.9 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 439.1 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 439.1 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 438.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 438.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 438.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 433.2 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 433.2 kB/s eta 0:00:15
   ------------ --------------------------- 2.8/9.1 MB 433.2 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 428.3 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 428.3 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 423.8 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 423.8 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 421.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 421.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 421.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 415.9 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 415.9 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 413.3 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.1 MB 413.3 kB/s eta 0:00:15
   ------------- -------------------------- 2.9/9.1 MB 410.7 kB/s eta 0:00:15
   ------------- -------------------------- 2.9/9.1 MB 410.7 kB/s eta 0:00:15
   ------------- -------------------------- 2.9/9.1 MB 410.7 kB/s eta 0:00:15
   ------------- -------------------------- 2.9/9.1 MB 410.7 kB/s eta 0:00:15
   ------------- -------------------------- 3.0/9.1 MB 403.5 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 403.5 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 403.5 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 399.0 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 399.0 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 395.1 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 395.1 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 393.0 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 393.0 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 393.0 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 393.0 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 385.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.0/9.1 MB 385.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.1 MB 383.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.1 MB 383.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.1 MB 379.8 kB/s eta 0:00:16

In [171]:
import pickle

In [172]:
pickle.dump(new_df, open('movies.pkl','wb'))

In [173]:
pickle.dump(similarity,open('similarity.pkl','wb'))